name: Gallery Update from Google Drive

on:
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias Python
        run: pip install gspread google-auth

      - name: Ejecutar script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: python infra/gallery_sync.py